const weatherCodesMeaning = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light Drizzle",
  53: "Modarate Drizzle",
  55: "Dense Drizzle",
  56: "Light Freezing Drizzle ",
  57: "Dense Freezing Drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  66: "Light freezing rain",
  67: "Heavy freezing rain",
  71: "Slight snow fall",
  73: "Moderate snow fall",
  75: "Heavy snow fall",
  77: "Snow grains",
  80: "Slight rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  85: "Slight snow showers",
  86: "Heavy snow showers",
  95: "Slight thunderstorm",
  96: "Moderate thunderstorm",
  99: "Heavy thunderstorm",

  100: "Clear sky",
  101: "Mainly clear",
  102: "Partly cloudy",
  103: "Overcast",
  145: "Fog",
  148: "Depositing rime fog",
  151: "Light Drizzle",
  153: "Modarate Drizzle",
  155: "Dense Drizzle",
  156: "Light Freezing Drizzle ",
  157: "Dense Freezing Drizzle",
  161: "Slight rain",
  163: "Moderate rain",
  165: "Heavy rain",
  166: "Light freezing rain",
  167: "Heavy freezing rain",
  171: "Slight snow fall",
  173: "Moderate snow fall",
  175: "Heavy snow fall",
  177: "Snow grains",
  180: "Slight rain showers",
  181: "Moderate rain showers",
  182: "Violent rain showers",
  185: "Slight snow showers",
  186: "Heavy snow showers",
  195: "Slight thunderstorm",
  196: "Moderate thunderstorm",
  199: "Heavy thunderstorm",
};

export default weatherCodesMeaning;
